# IMV during GNN training: six graph benchmarks

This is a documented reconstruction of Section 6 / Figure 5 and Appendix F.3 of *Mastering Model Fit: Applications of the InterModel Vigorish for Interpretable Machine Learning*. In the supplied PDF, the appendix learning curves are **Figure A6**, not A5.

The six examples are **PROTEINS, NCI1, NCI109, Mutagenicity, AIDS, and DD**. All are the original public [TU graph datasets](https://chrsmrrs.github.io/datasets/docs/datasets/), not tabular substitutes or synthetic stand-ins. This notebook produces results only. Figures are rebuilt separately in `src/plotter/plotter.ipynb`, together with the ablation overview.

## Reconstruction protocol

| Item | Protocol | Evidence / choice |
|---|---|---|
| Architecture | Three GCN layers | Paper Section 5.1.3 |
| Training | Adam, learning rate 0.001, logical batch size 512, 200 epochs | Paper Section 5.1.3 and Figure 5; Adam is an explicit implementation choice |
| Split | Stratified 70% train / 15% validation / 15% test, split anew for each seed | Appendix D.4; stratification and extension to appendix datasets are explicit choices |
| Replicates | Seeds 42-51, ten independent training runs per dataset | Requested extension from the paper's five runs |
| Unspecified architecture | Hidden width 64, ReLU after each GCN, global mean pooling, dropout 0.5 before a one-logit classifier, no weight decay | Fixed in advance; not tuned on test results |
| Features | Provided one-hot node labels plus continuous node attributes; continuous columns standardized using training nodes only | [PyG TUDataset](https://pytorch-geometric.readthedocs.io/en/2.7.0/generated/torch_geometric.datasets.TUDataset.html); no outcome features |
| Optional engineering | `native+degree` appends standardized log(1 + degree) | Separate, fingerprinted experiment; not the default reconstruction |
| Graph structure | Undirected unweighted edges, duplicate removal, one self-loop per node, symmetric GCN normalization | [GCNConv definition](https://pytorch-geometric.readthedocs.io/en/2.7.0/generated/torch_geometric.nn.conv.GCNConv.html) |
| Edge labels | Not used by this ordinary GCN | Explicit limitation for molecular datasets with bond labels |
| Epoch evaluation | Validation and test predictions at epoch 0 and every epoch 1-200 | Epoch 0 is an added untrained-model diagnostic |
| Selection | Fixed 200 epochs; no early stopping, test-based tuning, or best-test-epoch selection | Prevents test curves from feeding back into model fitting |

Original TU datasets can contain isomorphic/duplicate graphs. We retain the original rather than the cleaned variants for comparability with the paper; random graph splits are not a scaffold split or a guarantee against isomorphism bias. Raw-file hashes, exact graph split IDs, feature scaling, label mapping, library versions, and configuration are recorded for every seed. Exact numerical reproduction is not claimed because the paper does not specify all implementation details.

In [1]:
import os
import sys
from pathlib import Path

PROJECT_ROOT = next(
    path for path in (Path.cwd(), *Path.cwd().parents)
    if (path / "src" / "empirical" / "gnn" / "gnn_training.py").is_file()
)
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

import pandas as pd
import torch
import imvpy
from empirical.gnn.gnn_training import DATASETS, SEEDS, GNNConfig, cache_paths, execution_plan, run_experiments

CONFIG = GNNConfig()
DEVICE = os.environ.get("IMV_GNN_DEVICE", "auto")
JOBS = int(os.environ["IMV_GNN_JOBS"]) if "IMV_GNN_JOBS" in os.environ else None
FRESH = os.environ.get("IMV_FORCE_RECOMPUTE", "0").strip().lower() in {"1", "true", "yes"}
DATA_ROOT, ARTIFACT_ROOT = cache_paths()
print(f"imvpy {imvpy.__version__}; PyTorch {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}; worker devices: {execution_plan(CONFIG, JOBS, DEVICE)}")
print(f"{len(DATASETS)} datasets x {len(SEEDS)} seeds x {CONFIG.epochs} epochs")
print("Data cache:", DATA_ROOT)
print("Result cache:", ARTIFACT_ROOT)

imvpy 1.2.0; PyTorch 2.9.0+cpu
CUDA available: False; worker devices: ['cpu', 'cpu', 'cpu', 'cpu', 'cpu', 'cpu']
6 datasets x 10 seeds x 200 epochs
Data cache: /home/jinx/.cache/imv/datasets/tu
Result cache: /home/jinx/.cache/imv/notebook_artifacts/gnn_training

## Metrics and seed ranges

**Evaluation is performed at every single epoch**, including epoch 0: 201 validation and 201 test evaluations per seed. The ten-epoch checkpoint interval and 25-epoch console logging interval do not subsample evaluation. The evaluation batches cache graph inputs, never predictions. Each epoch uses the current model in evaluation mode (dropout disabled), with no temporal averaging, parameter averaging, or ensembling across epochs.

**IMV is primary.** Each epoch uses `imvpy.imv_from_likelihoods(ll(y, p_null), ll(y, p_gcn))`. The null predicts the **training-set prevalence**, evaluated on the same held-out graphs as the GCN. The paper does not specify the Section 6 null explicitly; this intercept-only choice reflects class imbalance and is fixed before evaluation. Unlike the ablation overview, it is not a constant 0.5 null. Fair-coin IMV and the null-dependent upper bound are also saved for audit.

Accuracy, binary precision, and binary recall use a fixed threshold of 0.5, following Appendix E.2.2. Positive class is the canonical TU/PyG label 1; the original label order is saved rather than guessing semantic class names. Undefined precision from zero positive predictions is reported as zero. Additional diagnostics include binary F1, ROC AUC, balanced accuracy, Brier score, log loss, macro/weighted precision and recall, geometric likelihood, and information deficit.

The pinned `imvpy` sometimes returns its chance-boundary value for mildly below-chance likelihoods; severely below-chance likelihoods yield NaN. We preserve and flag that behavior. **Negative IMV is retained.** Undefined IMVs are not replaced with zero. A plotted point and its range require all ten finite seed values; incomplete points are gaps and the coverage table reports them.

Lines show the **mean across ten seeds**. The shaded band follows the **minimum and maximum seed values at every epoch** along each mean curve, computed separately for each dataset and metric. Individual seed lines are omitted from the overview. These are observed seed ranges, **not confidence intervals**. A separate IMV figure shows every seed without averaging and uses explicitly labelled dataset-specific y-axis ranges. No smoothing, renderer path simplification, monotonicity constraint, or curve matching is used. The plotter calculates these ranges from the saved per-seed metrics; the original CI description in training manifests is historical and does not control plotting. Training code and checkpoint fingerprints are unchanged.

## Execution and restart behavior

Training is a full 60-run experiment. CPU execution uses bounded, separate seed-worker processes with a fixed thread budget. With CUDA-enabled PyTorch and a working driver, `IMV_GNN_DEVICE=auto` uses one process per visible GPU, distributing independent runs across devices. `CUDA_VISIBLE_DEVICES` selects GPUs; `IMV_GNN_JOBS` can limit workers. A single GPU is not oversubscribed by default.

Graph normalization is cached. Sparse matrix multiplication avoids large edge-message tensors; node-budgeted microbatches accumulate gradients into the same 512-graph optimizer batch. Validation/test batches are reused. Deterministic algorithms are required; unsupported GPU kernels fail visibly rather than silently relaxing reproducibility. No mixed precision is enabled. Bitwise equality between CPU and GPU or across library versions is not promised.

Each job checkpoints model, Adam state, RNG state, epoch history, and test-probability history every ten epochs. Resuming restores the last complete checkpoint. Changes to data, code, model configuration, or numerical environment invalidate a cached job; changing only worker count does not. Concurrent invocations are locked. Completed test-probability traces allow every reported test metric to be audited without refitting.

The defaults produce publication results. Smaller configurations, subsets, or fewer seeds are written under a separate `checks/` directory and cannot overwrite or satisfy the publication plotter. `IMV_FORCE_RECOMPUTE=1` bypasses checkpoints. Do not use `run_all.sh --fresh` unless you intend to rerun every project example.

In [2]:
epoch_metrics, result_directory = run_experiments(
    CONFIG, datasets=DATASETS, seeds=SEEDS, jobs=JOBS, device=DEVICE,
    data_root=DATA_ROOT, artifact_root=ARTIFACT_ROOT, fresh=FRESH,
)
print("Completed GNN results:", result_directory)

GNN: 60 runs x 200 epochs; devices=['cpu', 'cpu', 'cpu', 'cpu', 'cpu', 'cpu']; 2 CPU threads/worker; features=native

PROTEINS seed 44 epoch 0/200: IMV=-0.1649, accuracy=0.4012
PROTEINS seed 46 epoch 0/200: IMV=-0.1565, accuracy=0.4072
PROTEINS seed 42 epoch 0/200: IMV=-0.1332, accuracy=0.6048
PROTEINS seed 45 epoch 0/200: IMV=-0.0462, accuracy=0.5928
PROTEINS seed 47 epoch 0/200: IMV=-0.0991, accuracy=0.6108
PROTEINS seed 43 epoch 0/200: IMV=-0.1649, accuracy=0.4012

PROTEINS seed 45 epoch 25/200: IMV=0.1486, accuracy=0.6527
PROTEINS seed 44 epoch 25/200: IMV=0.0640, accuracy=0.6287
PROTEINS seed 43 epoch 25/200: IMV=0.0629, accuracy=0.6228
PROTEINS seed 47 epoch 25/200: IMV=0.1107, accuracy=0.6347
PROTEINS seed 42 epoch 25/200: IMV=0.0635, accuracy=0.6228

PROTEINS seed 46 epoch 25/200: IMV=0.0831, accuracy=0.6347

PROTEINS seed 44 epoch 50/200: IMV=0.0872, accuracy=0.6587

PROTEINS seed 45 epoch 50/200: IMV=0.2279, accuracy=0.7186
PROTEINS seed 47 epoch 50/200: IMV=0.1978, accuracy=0.7186
PROTEINS seed 43 epoch 50/200: IMV=0.1624, accuracy=0.6886

PROTEINS seed 42 epoch 50/200: IMV=0.1415, accuracy=0.6707

PROTEINS seed 46 epoch 50/200: IMV=0.1907, accuracy=0.7066

PROTEINS seed 44 epoch 75/200: IMV=0.0908, accuracy=0.6766

PROTEINS seed 47 epoch 75/200: IMV=0.2005, accuracy=0.7186
PROTEINS seed 45 epoch 75/200: IMV=0.2446, accuracy=0.7006
PROTEINS seed 43 epoch 75/200: IMV=0.1756, accuracy=0.6946

PROTEINS seed 46 epoch 75/200: IMV=0.2021, accuracy=0.7006
PROTEINS seed 42 epoch 75/200: IMV=0.1454, accuracy=0.6766

PROTEINS seed 44 epoch 100/200: IMV=0.0959, accuracy=0.6826
PROTEINS seed 47 epoch 100/200: IMV=0.2111, accuracy=0.7246

PROTEINS seed 45 epoch 100/200: IMV=0.2496, accuracy=0.6886

PROTEINS seed 43 epoch 100/200: IMV=0.1767, accuracy=0.6826

PROTEINS seed 46 epoch 100/200: IMV=0.1961, accuracy=0.7006
PROTEINS seed 47 epoch 125/200: IMV=0.2101, accuracy=0.7246

PROTEINS seed 42 epoch 100/200: IMV=0.1476, accuracy=0.7006

PROTEINS seed 45 epoch 125/200: IMV=0.2553, accuracy=0.7006

PROTEINS seed 44 epoch 125/200: IMV=0.1035, accuracy=0.6826
PROTEINS seed 47 epoch 150/200: IMV=0.2144, accuracy=0.7305

PROTEINS seed 46 epoch 125/200: IMV=0.1967, accuracy=0.7066

PROTEINS seed 42 epoch 125/200: IMV=0.1507, accuracy=0.7066

PROTEINS seed 43 epoch 125/200: IMV=0.1878, accuracy=0.7006

PROTEINS seed 45 epoch 150/200: IMV=0.2580, accuracy=0.7066

PROTEINS seed 46 epoch 150/200: IMV=0.1942, accuracy=0.6886

PROTEINS seed 47 epoch 175/200: IMV=0.2220, accuracy=0.7305

PROTEINS seed 44 epoch 150/200: IMV=0.1060, accuracy=0.6707

PROTEINS seed 42 epoch 150/200: IMV=0.1539, accuracy=0.7006
PROTEINS seed 43 epoch 150/200: IMV=0.1972, accuracy=0.7186

PROTEINS seed 46 epoch 175/200: IMV=0.1933, accuracy=0.6766
PROTEINS seed 45 epoch 175/200: IMV=0.2619, accuracy=0.7126

PROTEINS seed 47 epoch 200/200: IMV=0.2202, accuracy=0.7066

NCI1 seed 43 epoch 0/200: IMV=-0.0015, accuracy=0.4992

PROTEINS seed 44 epoch 175/200: IMV=0.1077, accuracy=0.6647

PROTEINS seed 43 epoch 175/200: IMV=0.2085, accuracy=0.7246
PROTEINS seed 46 epoch 200/200: IMV=0.1940, accuracy=0.7066

PROTEINS seed 42 epoch 175/200: IMV=0.1641, accuracy=0.7006
NCI1 seed 42 epoch 0/200: IMV=-0.0015, accuracy=0.4992
PROTEINS seed 45 epoch 200/200: IMV=0.2618, accuracy=0.7126
PROTEINS seed 51 epoch 0/200: IMV=-0.1649, accuracy=0.4012

PROTEINS seed 44 epoch 200/200: IMV=0.1093, accuracy=0.6587
PROTEINS seed 50 epoch 0/200: IMV=-0.0943, accuracy=0.6048

PROTEINS seed 43 epoch 200/200: IMV=0.2192, accuracy=0.7246
PROTEINS seed 49 epoch 0/200: IMV=-0.0836, accuracy=0.5988

PROTEINS seed 51 epoch 25/200: IMV=0.0745, accuracy=0.6287

PROTEINS seed 42 epoch 200/200: IMV=0.1667, accuracy=0.7066
PROTEINS seed 49 epoch 25/200: IMV=0.1105, accuracy=0.6407
PROTEINS seed 48 epoch 0/200: IMV=-0.0488, accuracy=0.5988

NCI1 seed 43 epoch 25/200: IMV=0.2598, accuracy=0.6240

PROTEINS seed 50 epoch 25/200: IMV=0.1262, accuracy=0.6527
PROTEINS seed 51 epoch 50/200: IMV=0.1809, accuracy=0.6946

PROTEINS seed 49 epoch 50/200: IMV=0.1854, accuracy=0.6946

NCI1 seed 42 epoch 25/200: IMV=0.2962, accuracy=0.6353

PROTEINS seed 50 epoch 50/200: IMV=0.1959, accuracy=0.7305
PROTEINS seed 51 epoch 75/200: IMV=0.1824, accuracy=0.6886

PROTEINS seed 48 epoch 25/200: IMV=0.0886, accuracy=0.6347

PROTEINS seed 49 epoch 75/200: IMV=0.2061, accuracy=0.7066

PROTEINS seed 50 epoch 75/200: IMV=0.2157, accuracy=0.7186

NCI1 seed 43 epoch 50/200: IMV=0.3608, accuracy=0.6629
PROTEINS seed 51 epoch 100/200: IMV=0.1922, accuracy=0.7006

PROTEINS seed 49 epoch 100/200: IMV=0.2118, accuracy=0.6946

PROTEINS seed 48 epoch 50/200: IMV=0.1208, accuracy=0.6647

PROTEINS seed 51 epoch 125/200: IMV=0.1947, accuracy=0.7066
PROTEINS seed 50 epoch 100/200: IMV=0.2432, accuracy=0.7246

NCI1 seed 42 epoch 50/200: IMV=0.3617, accuracy=0.6499

PROTEINS seed 49 epoch 125/200: IMV=0.2226, accuracy=0.7006

PROTEINS seed 51 epoch 150/200: IMV=0.2069, accuracy=0.7066

PROTEINS seed 50 epoch 125/200: IMV=0.2555, accuracy=0.7425

PROTEINS seed 48 epoch 75/200: IMV=0.1545, accuracy=0.6707
NCI1 seed 43 epoch 75/200: IMV=0.4026, accuracy=0.6904

PROTEINS seed 49 epoch 150/200: IMV=0.2242, accuracy=0.7126

PROTEINS seed 51 epoch 175/200: IMV=0.2159, accuracy=0.7186

PROTEINS seed 50 epoch 150/200: IMV=0.2678, accuracy=0.7485

PROTEINS seed 49 epoch 175/200: IMV=0.2290, accuracy=0.7126

PROTEINS seed 51 epoch 200/200: IMV=0.2115, accuracy=0.7006
PROTEINS seed 50 epoch 175/200: IMV=0.2784, accuracy=0.7485

PROTEINS seed 48 epoch 100/200: IMV=0.1812, accuracy=0.6766

NCI1 seed 47 epoch 0/200: IMV=-0.0015, accuracy=0.4992

NCI1 seed 42 epoch 75/200: IMV=0.3872, accuracy=0.6759
PROTEINS seed 49 epoch 200/200: IMV=0.2322, accuracy=0.7186

NCI1 seed 43 epoch 100/200: IMV=0.4153, accuracy=0.6985

NCI1 seed 45 epoch 0/200: IMV=-0.0015, accuracy=0.5008

PROTEINS seed 50 epoch 200/200: IMV=0.2855, accuracy=0.7725

NCI1 seed 46 epoch 0/200: IMV=-0.0015, accuracy=0.5008

PROTEINS seed 48 epoch 125/200: IMV=0.2027, accuracy=0.6886

NCI1 seed 47 epoch 25/200: IMV=0.3228, accuracy=0.6483
NCI1 seed 43 epoch 125/200: IMV=0.4179, accuracy=0.6823

NCI1 seed 45 epoch 25/200: IMV=0.2744, accuracy=0.6240

PROTEINS seed 48 epoch 150/200: IMV=0.2106, accuracy=0.7066

NCI1 seed 46 epoch 25/200: IMV=0.2677, accuracy=0.5981

NCI1 seed 42 epoch 100/200: IMV=0.4066, accuracy=0.6840

NCI1 seed 43 epoch 150/200: IMV=0.4111, accuracy=0.6823

NCI1 seed 47 epoch 50/200: IMV=0.3930, accuracy=0.6904

PROTEINS seed 48 epoch 175/200: IMV=0.2057, accuracy=0.6946

NCI1 seed 45 epoch 50/200: IMV=0.3640, accuracy=0.6499

PROTEINS seed 48 epoch 200/200: IMV=0.2202, accuracy=0.7066

NCI1 seed 44 epoch 0/200: IMV=-0.0015, accuracy=0.5008

NCI1 seed 46 epoch 50/200: IMV=0.3623, accuracy=0.6451

NCI1 seed 43 epoch 175/200: IMV=0.4138, accuracy=0.7099

NCI1 seed 47 epoch 75/200: IMV=0.4270, accuracy=0.7131
NCI1 seed 45 epoch 75/200: IMV=0.4107, accuracy=0.6742

NCI1 seed 42 epoch 125/200: IMV=0.4097, accuracy=0.6856

NCI1 seed 44 epoch 25/200: IMV=0.2925, accuracy=0.6515

NCI1 seed 46 epoch 75/200: IMV=0.3962, accuracy=0.6710
NCI1 seed 43 epoch 200/200: IMV=0.4211, accuracy=0.7083

NCI1 seed 49 epoch 0/200: IMV=-0.0015, accuracy=0.4992

NCI1 seed 47 epoch 100/200: IMV=0.4293, accuracy=0.6872

NCI1 seed 44 epoch 50/200: IMV=0.3631, accuracy=0.6921

NCI1 seed 42 epoch 150/200: IMV=0.4141, accuracy=0.6759

NCI1 seed 45 epoch 100/200: IMV=0.4216, accuracy=0.6791

NCI1 seed 46 epoch 100/200: IMV=0.4114, accuracy=0.6742

NCI1 seed 49 epoch 25/200: IMV=0.3046, accuracy=0.6451
NCI1 seed 47 epoch 125/200: IMV=0.4361, accuracy=0.7196

NCI1 seed 44 epoch 75/200: IMV=0.3879, accuracy=0.6888
NCI1 seed 42 epoch 175/200: IMV=0.4183, accuracy=0.6791

NCI1 seed 45 epoch 125/200: IMV=0.4352, accuracy=0.6921
NCI1 seed 46 epoch 125/200: IMV=0.3912, accuracy=0.6840

NCI1 seed 47 epoch 150/200: IMV=0.4391, accuracy=0.7342

NCI1 seed 42 epoch 200/200: IMV=0.4213, accuracy=0.6840
NCI1 seed 48 epoch 0/200: IMV=-0.0015, accuracy=0.4992

NCI1 seed 44 epoch 100/200: IMV=0.3985, accuracy=0.6742

NCI1 seed 49 epoch 50/200: IMV=0.3714, accuracy=0.6532

NCI1 seed 46 epoch 150/200: IMV=0.4053, accuracy=0.6823

NCI1 seed 45 epoch 150/200: IMV=0.4430, accuracy=0.6921

NCI1 seed 47 epoch 175/200: IMV=0.4366, accuracy=0.7196
NCI1 seed 48 epoch 25/200: IMV=0.2556, accuracy=0.5997

NCI1 seed 46 epoch 175/200: IMV=0.4161, accuracy=0.6823

NCI1 seed 49 epoch 75/200: IMV=0.3920, accuracy=0.6759

NCI1 seed 44 epoch 125/200: IMV=0.4050, accuracy=0.6726

NCI1 seed 45 epoch 175/200: IMV=0.4445, accuracy=0.6856
NCI1 seed 47 epoch 200/200: IMV=0.4388, accuracy=0.7310

NCI109 seed 43 epoch 0/200: IMV=-0.0063, accuracy=0.5032
NCI1 seed 46 epoch 200/200: IMV=0.4153, accuracy=0.6953

NCI1 seed 48 epoch 50/200: IMV=0.3040, accuracy=0.6175

NCI109 seed 42 epoch 0/200: IMV=-0.0063, accuracy=0.5032

NCI1 seed 49 epoch 100/200: IMV=0.3998, accuracy=0.6759

NCI1 seed 45 epoch 200/200: IMV=0.4520, accuracy=0.6953
NCI1 seed 51 epoch 0/200: IMV=-0.0015, accuracy=0.5008

NCI109 seed 43 epoch 25/200: IMV=0.1916, accuracy=0.5919

NCI109 seed 42 epoch 25/200: IMV=0.2125, accuracy=0.6210

NCI1 seed 44 epoch 150/200: IMV=0.4180, accuracy=0.6807

NCI1 seed 48 epoch 75/200: IMV=0.3433, accuracy=0.6580

NCI1 seed 49 epoch 125/200: IMV=0.4069, accuracy=0.6840

NCI1 seed 51 epoch 25/200: IMV=0.2719, accuracy=0.6451
NCI109 seed 42 epoch 50/200: IMV=0.3089, accuracy=0.6435

NCI109 seed 43 epoch 50/200: IMV=0.3518, accuracy=0.6597

NCI1 seed 49 epoch 150/200: IMV=0.4113, accuracy=0.6856

NCI1 seed 48 epoch 100/200: IMV=0.3514, accuracy=0.6645

NCI1 seed 44 epoch 175/200: IMV=0.4234, accuracy=0.6856

NCI1 seed 51 epoch 50/200: IMV=0.3581, accuracy=0.6888
NCI109 seed 43 epoch 75/200: IMV=0.3808, accuracy=0.6694
NCI109 seed 42 epoch 75/200: IMV=0.3324, accuracy=0.6452

NCI1 seed 49 epoch 175/200: IMV=0.3990, accuracy=0.6515

NCI1 seed 48 epoch 125/200: IMV=0.3501, accuracy=0.6710

NCI1 seed 51 epoch 75/200: IMV=0.3680, accuracy=0.6775

NCI109 seed 42 epoch 100/200: IMV=0.3310, accuracy=0.6613

NCI1 seed 44 epoch 200/200: IMV=0.4322, accuracy=0.6921
NCI1 seed 50 epoch 0/200: IMV=-0.0015, accuracy=0.4992

NCI109 seed 43 epoch 100/200: IMV=0.3965, accuracy=0.6758

NCI1 seed 48 epoch 150/200: IMV=0.3464, accuracy=0.6710

NCI1 seed 51 epoch 100/200: IMV=0.3689, accuracy=0.7083

NCI109 seed 42 epoch 125/200: IMV=0.3332, accuracy=0.6516

NCI1 seed 49 epoch 200/200: IMV=0.4189, accuracy=0.6807

NCI1 seed 50 epoch 25/200: IMV=0.2811, accuracy=0.6321

NCI109 seed 45 epoch 0/200: IMV=0.0061, accuracy=0.4968

NCI109 seed 43 epoch 125/200: IMV=0.3904, accuracy=0.7016

NCI1 seed 48 epoch 175/200: IMV=0.3374, accuracy=0.6645
NCI1 seed 51 epoch 125/200: IMV=0.3550, accuracy=0.6953

NCI109 seed 42 epoch 150/200: IMV=0.3346, accuracy=0.6597

NCI1 seed 50 epoch 50/200: IMV=0.3543, accuracy=0.6677

NCI109 seed 43 epoch 150/200: IMV=0.3949, accuracy=0.7048

NCI1 seed 51 epoch 150/200: IMV=0.3586, accuracy=0.7131

NCI1 seed 48 epoch 200/200: IMV=0.3061, accuracy=0.6775

NCI109 seed 44 epoch 0/200: IMV=-0.0063, accuracy=0.5032
NCI109 seed 45 epoch 25/200: IMV=0.3015, accuracy=0.6371

NCI109 seed 42 epoch 175/200: IMV=0.3329, accuracy=0.6645

NCI1 seed 50 epoch 75/200: IMV=0.3383, accuracy=0.6694

NCI109 seed 43 epoch 175/200: IMV=0.4051, accuracy=0.7177

NCI109 seed 44 epoch 25/200: IMV=0.2838, accuracy=0.6339

NCI1 seed 50 epoch 100/200: IMV=0.3538, accuracy=0.6726

NCI109 seed 45 epoch 50/200: IMV=0.3686, accuracy=0.6548

NCI109 seed 42 epoch 200/200: IMV=0.3230, accuracy=0.6532
NCI109 seed 48 epoch 0/200: IMV=-0.0063, accuracy=0.5032

NCI1 seed 51 epoch 175/200: IMV=0.3437, accuracy=0.7050

NCI109 seed 44 epoch 50/200: IMV=0.3885, accuracy=0.6726

NCI1 seed 50 epoch 125/200: IMV=0.3484, accuracy=0.6759

NCI109 seed 43 epoch 200/200: IMV=0.4005, accuracy=0.7081
NCI109 seed 49 epoch 0/200: IMV=-0.0063, accuracy=0.4968

NCI109 seed 48 epoch 25/200: IMV=0.2380, accuracy=0.6048
NCI109 seed 45 epoch 75/200: IMV=0.3890, accuracy=0.6629

NCI1 seed 51 epoch 200/200: IMV=0.3389, accuracy=0.6840

NCI109 seed 44 epoch 75/200: IMV=0.4122, accuracy=0.6758

NCI109 seed 47 epoch 0/200: IMV=-0.0063, accuracy=0.4968

NCI109 seed 49 epoch 25/200: IMV=0.2692, accuracy=0.6355

NCI109 seed 48 epoch 50/200: IMV=0.3288, accuracy=0.6548

NCI109 seed 45 epoch 100/200: IMV=0.3940, accuracy=0.6645

NCI1 seed 50 epoch 150/200: IMV=0.3465, accuracy=0.6953

NCI109 seed 44 epoch 100/200: IMV=0.4207, accuracy=0.6790

NCI109 seed 47 epoch 25/200: IMV=0.2643, accuracy=0.6355

NCI109 seed 49 epoch 50/200: IMV=0.3434, accuracy=0.6645

NCI109 seed 44 epoch 125/200: IMV=0.4138, accuracy=0.6694

NCI1 seed 50 epoch 175/200: IMV=0.3333, accuracy=0.7034
NCI109 seed 45 epoch 125/200: IMV=0.3941, accuracy=0.6774

NCI109 seed 48 epoch 75/200: IMV=0.3437, accuracy=0.6548

NCI109 seed 47 epoch 50/200: IMV=0.3333, accuracy=0.6677

NCI109 seed 49 epoch 75/200: IMV=0.3674, accuracy=0.6806

NCI109 seed 44 epoch 150/200: IMV=0.4321, accuracy=0.6855

NCI109 seed 45 epoch 150/200: IMV=0.4002, accuracy=0.6790

NCI109 seed 48 epoch 100/200: IMV=0.3545, accuracy=0.6500

NCI1 seed 50 epoch 200/200: IMV=0.3338, accuracy=0.6921

NCI109 seed 49 epoch 100/200: IMV=0.3762, accuracy=0.6790
NCI109 seed 46 epoch 0/200: IMV=-0.0063, accuracy=0.5032

NCI109 seed 47 epoch 75/200: IMV=0.3402, accuracy=0.6645

NCI109 seed 44 epoch 175/200: IMV=0.4358, accuracy=0.6871

NCI109 seed 48 epoch 125/200: IMV=0.3642, accuracy=0.6597

NCI109 seed 45 epoch 175/200: IMV=0.3965, accuracy=0.6919

NCI109 seed 49 epoch 125/200: IMV=0.3822, accuracy=0.6839

NCI109 seed 46 epoch 25/200: IMV=0.2904, accuracy=0.6468

NCI109 seed 44 epoch 200/200: IMV=0.4412, accuracy=0.6984
NCI109 seed 50 epoch 0/200: IMV=-0.0063, accuracy=0.5032

NCI109 seed 48 epoch 150/200: IMV=0.3599, accuracy=0.6565

NCI109 seed 47 epoch 100/200: IMV=0.3500, accuracy=0.6758

NCI109 seed 46 epoch 50/200: IMV=0.3716, accuracy=0.6774

NCI109 seed 45 epoch 200/200: IMV=0.3980, accuracy=0.6887
NCI109 seed 51 epoch 0/200: IMV=-0.0063, accuracy=0.5032

NCI109 seed 49 epoch 150/200: IMV=0.3829, accuracy=0.6871

NCI109 seed 50 epoch 25/200: IMV=0.2688, accuracy=0.6145

NCI109 seed 48 epoch 175/200: IMV=0.3749, accuracy=0.6597

NCI109 seed 46 epoch 75/200: IMV=0.3772, accuracy=0.6839

NCI109 seed 50 epoch 50/200: IMV=0.3604, accuracy=0.6565

NCI109 seed 49 epoch 175/200: IMV=0.3660, accuracy=0.6613

NCI109 seed 51 epoch 25/200: IMV=0.2240, accuracy=0.6161
NCI109 seed 47 epoch 125/200: IMV=0.3486, accuracy=0.6806

NCI109 seed 48 epoch 200/200: IMV=0.3679, accuracy=0.6677

Mutagenicity seed 44 epoch 0/200: IMV=-0.0983, accuracy=0.4455

NCI109 seed 50 epoch 75/200: IMV=0.3688, accuracy=0.6661

NCI109 seed 49 epoch 200/200: IMV=0.3885, accuracy=0.6984

NCI109 seed 46 epoch 100/200: IMV=0.3814, accuracy=0.6839

Mutagenicity seed 45 epoch 0/200: IMV=-0.0519, accuracy=0.5545

Mutagenicity seed 44 epoch 25/200: IMV=0.3407, accuracy=0.7127

NCI109 seed 51 epoch 50/200: IMV=0.2977, accuracy=0.6290

NCI109 seed 50 epoch 100/200: IMV=0.3771, accuracy=0.6629

Mutagenicity seed 45 epoch 25/200: IMV=0.2739, accuracy=0.6759

NCI109 seed 47 epoch 150/200: IMV=0.3467, accuracy=0.6806

NCI109 seed 46 epoch 125/200: IMV=0.3708, accuracy=0.6903
Mutagenicity seed 44 epoch 50/200: IMV=0.3956, accuracy=0.7481

NCI109 seed 51 epoch 75/200: IMV=0.3179, accuracy=0.6548

Mutagenicity seed 45 epoch 50/200: IMV=0.3452, accuracy=0.7112

NCI109 seed 50 epoch 125/200: IMV=0.3810, accuracy=0.6742
NCI109 seed 47 epoch 175/200: IMV=0.3408, accuracy=0.6806

NCI109 seed 46 epoch 150/200: IMV=0.3582, accuracy=0.6613

Mutagenicity seed 44 epoch 75/200: IMV=0.4282, accuracy=0.7542

Mutagenicity seed 45 epoch 75/200: IMV=0.3807, accuracy=0.7235

NCI109 seed 51 epoch 100/200: IMV=0.3335, accuracy=0.6500

NCI109 seed 47 epoch 200/200: IMV=0.3370, accuracy=0.6919

Mutagenicity seed 43 epoch 0/200: IMV=-0.0627, accuracy=0.5545

NCI109 seed 50 epoch 150/200: IMV=0.3904, accuracy=0.6774

Mutagenicity seed 45 epoch 100/200: IMV=0.3983, accuracy=0.7327

Mutagenicity seed 44 epoch 100/200: IMV=0.4585, accuracy=0.7711

NCI109 seed 51 epoch 125/200: IMV=0.3357, accuracy=0.6516
NCI109 seed 46 epoch 175/200: IMV=0.3632, accuracy=0.6726

Mutagenicity seed 43 epoch 25/200: IMV=0.3173, accuracy=0.7143

NCI109 seed 50 epoch 175/200: IMV=0.3791, accuracy=0.6710

Mutagenicity seed 45 epoch 125/200: IMV=0.4026, accuracy=0.7343

Mutagenicity seed 44 epoch 125/200: IMV=0.4693, accuracy=0.7680

NCI109 seed 51 epoch 150/200: IMV=0.3299, accuracy=0.6581

Mutagenicity seed 43 epoch 50/200: IMV=0.3847, accuracy=0.7343

Mutagenicity seed 45 epoch 150/200: IMV=0.4047, accuracy=0.7343

Mutagenicity seed 44 epoch 150/200: IMV=0.4788, accuracy=0.7773
NCI109 seed 46 epoch 200/200: IMV=0.3470, accuracy=0.7000

Mutagenicity seed 42 epoch 0/200: IMV=-0.0120, accuracy=0.5545

Mutagenicity seed 43 epoch 75/200: IMV=0.4120, accuracy=0.7619

NCI109 seed 51 epoch 175/200: IMV=0.3390, accuracy=0.6548

NCI109 seed 50 epoch 200/200: IMV=0.4050, accuracy=0.6806

Mutagenicity seed 45 epoch 175/200: IMV=0.4063, accuracy=0.7343

Mutagenicity seed 46 epoch 0/200: IMV=-0.0278, accuracy=0.5545

Mutagenicity seed 44 epoch 175/200: IMV=0.4827, accuracy=0.7788

Mutagenicity seed 43 epoch 100/200: IMV=0.4349, accuracy=0.7604

NCI109 seed 51 epoch 200/200: IMV=0.3407, accuracy=0.6548

Mutagenicity seed 42 epoch 25/200: IMV=0.2892, accuracy=0.6836

Mutagenicity seed 45 epoch 200/200: IMV=0.4064, accuracy=0.7389
Mutagenicity seed 47 epoch 0/200: IMV=-0.0983, accuracy=0.4455
Mutagenicity seed 51 epoch 0/200: IMV=-0.0134, accuracy=0.5545

Mutagenicity seed 44 epoch 200/200: IMV=0.4860, accuracy=0.7896
Mutagenicity seed 50 epoch 0/200: IMV=-0.0983, accuracy=0.4455

Mutagenicity seed 47 epoch 25/200: IMV=0.2669, accuracy=0.6667
Mutagenicity seed 46 epoch 25/200: IMV=0.3080, accuracy=0.7112

Mutagenicity seed 51 epoch 25/200: IMV=0.3065, accuracy=0.6866
Mutagenicity seed 43 epoch 125/200: IMV=0.4436, accuracy=0.7588

Mutagenicity seed 42 epoch 50/200: IMV=0.3503, accuracy=0.7204

Mutagenicity seed 47 epoch 50/200: IMV=0.3594, accuracy=0.7020

Mutagenicity seed 50 epoch 25/200: IMV=0.2878, accuracy=0.6959

Mutagenicity seed 42 epoch 75/200: IMV=0.3780, accuracy=0.7296

Mutagenicity seed 51 epoch 50/200: IMV=0.3769, accuracy=0.7404

Mutagenicity seed 46 epoch 50/200: IMV=0.3746, accuracy=0.7158

Mutagenicity seed 47 epoch 75/200: IMV=0.3980, accuracy=0.7158

Mutagenicity seed 43 epoch 150/200: IMV=0.4464, accuracy=0.7527

Mutagenicity seed 42 epoch 100/200: IMV=0.3936, accuracy=0.7266

Mutagenicity seed 47 epoch 100/200: IMV=0.4259, accuracy=0.7373
Mutagenicity seed 46 epoch 75/200: IMV=0.4059, accuracy=0.7465

Mutagenicity seed 51 epoch 75/200: IMV=0.4147, accuracy=0.7465

Mutagenicity seed 50 epoch 50/200: IMV=0.3527, accuracy=0.7465

Mutagenicity seed 43 epoch 175/200: IMV=0.4531, accuracy=0.7680

Mutagenicity seed 42 epoch 125/200: IMV=0.4130, accuracy=0.7327

Mutagenicity seed 46 epoch 100/200: IMV=0.4306, accuracy=0.7634
Mutagenicity seed 47 epoch 125/200: IMV=0.4409, accuracy=0.7588

Mutagenicity seed 51 epoch 100/200: IMV=0.4385, accuracy=0.7665

Mutagenicity seed 43 epoch 200/200: IMV=0.4535, accuracy=0.7680
Mutagenicity seed 49 epoch 0/200: IMV=-0.0983, accuracy=0.4455

Mutagenicity seed 46 epoch 125/200: IMV=0.4445, accuracy=0.7604
Mutagenicity seed 50 epoch 75/200: IMV=0.3852, accuracy=0.7343

Mutagenicity seed 42 epoch 150/200: IMV=0.4250, accuracy=0.7419

Mutagenicity seed 51 epoch 125/200: IMV=0.4499, accuracy=0.7665

Mutagenicity seed 47 epoch 150/200: IMV=0.4525, accuracy=0.7558

Mutagenicity seed 51 epoch 150/200: IMV=0.4493, accuracy=0.7619

Mutagenicity seed 49 epoch 25/200: IMV=0.2933, accuracy=0.7143

Mutagenicity seed 47 epoch 175/200: IMV=0.4529, accuracy=0.7650
Mutagenicity seed 42 epoch 175/200: IMV=0.4314, accuracy=0.7512

Mutagenicity seed 46 epoch 150/200: IMV=0.4515, accuracy=0.7650

Mutagenicity seed 50 epoch 100/200: IMV=0.4110, accuracy=0.7619

Mutagenicity seed 47 epoch 200/200: IMV=0.4562, accuracy=0.7558
Mutagenicity seed 51 epoch 175/200: IMV=0.4576, accuracy=0.7634

AIDS seed 43 epoch 0/200: IMV=-0.3750, accuracy=0.2067

Mutagenicity seed 42 epoch 200/200: IMV=0.4365, accuracy=0.7496
Mutagenicity seed 48 epoch 0/200: IMV=-0.0983, accuracy=0.4455

Mutagenicity seed 49 epoch 50/200: IMV=0.3449, accuracy=0.7266

Mutagenicity seed 46 epoch 175/200: IMV=0.4569, accuracy=0.7711

AIDS seed 43 epoch 25/200: IMV=0.2004, accuracy=0.9500

Mutagenicity seed 50 epoch 125/200: IMV=0.4139, accuracy=0.7542

AIDS seed 43 epoch 50/200: IMV=0.2323, accuracy=0.9733

Mutagenicity seed 51 epoch 200/200: IMV=0.4622, accuracy=0.7680

AIDS seed 47 epoch 0/200: IMV=-0.2203, accuracy=0.8000

Mutagenicity seed 48 epoch 25/200: IMV=0.2839, accuracy=0.6774
Mutagenicity seed 46 epoch 200/200: IMV=0.4605, accuracy=0.7742

AIDS seed 42 epoch 0/200: IMV=-0.3750, accuracy=0.1400

AIDS seed 47 epoch 25/200: IMV=0.2135, accuracy=0.9700
AIDS seed 43 epoch 75/200: IMV=0.2375, accuracy=0.9867
Mutagenicity seed 49 epoch 75/200: IMV=0.3766, accuracy=0.7358

AIDS seed 42 epoch 25/200: IMV=0.1889, accuracy=0.9300

Mutagenicity seed 50 epoch 150/200: IMV=0.4165, accuracy=0.7650
AIDS seed 47 epoch 50/200: IMV=0.2347, accuracy=0.9833

AIDS seed 43 epoch 100/200: IMV=0.2382, accuracy=0.9833

AIDS seed 42 epoch 50/200: IMV=0.2374, accuracy=0.9900

AIDS seed 43 epoch 125/200: IMV=0.2381, accuracy=0.9833
AIDS seed 47 epoch 75/200: IMV=0.2412, accuracy=0.9900

AIDS seed 42 epoch 75/200: IMV=0.2421, accuracy=0.9933

Mutagenicity seed 49 epoch 100/200: IMV=0.3939, accuracy=0.7296
Mutagenicity seed 48 epoch 50/200: IMV=0.3529, accuracy=0.6974
AIDS seed 43 epoch 150/200: IMV=0.2379, accuracy=0.9833

AIDS seed 47 epoch 100/200: IMV=0.2417, accuracy=0.9900
AIDS seed 42 epoch 100/200: IMV=0.2427, accuracy=0.9933

AIDS seed 43 epoch 175/200: IMV=0.2373, accuracy=0.9800

AIDS seed 47 epoch 125/200: IMV=0.2420, accuracy=0.9900
AIDS seed 42 epoch 125/200: IMV=0.2430, accuracy=0.9933

AIDS seed 47 epoch 150/200: IMV=0.2422, accuracy=0.9867
Mutagenicity seed 50 epoch 175/200: IMV=0.4172, accuracy=0.7650
AIDS seed 42 epoch 150/200: IMV=0.2432, accuracy=0.9900

AIDS seed 43 epoch 200/200: IMV=0.2376, accuracy=0.9800

AIDS seed 49 epoch 0/200: IMV=-0.2589, accuracy=0.7900
Mutagenicity seed 49 epoch 125/200: IMV=0.3998, accuracy=0.7373
Mutagenicity seed 48 epoch 75/200: IMV=0.3779, accuracy=0.7035

AIDS seed 47 epoch 175/200: IMV=0.2416, accuracy=0.9833
AIDS seed 42 epoch 175/200: IMV=0.2435, accuracy=0.9900

AIDS seed 49 epoch 25/200: IMV=0.1940, accuracy=0.9267

AIDS seed 47 epoch 200/200: IMV=0.2395, accuracy=0.9767

AIDS seed 42 epoch 200/200: IMV=0.2434, accuracy=0.9867
AIDS seed 48 epoch 0/200: IMV=-0.3750, accuracy=0.1733

DD seed 43 epoch 0/200: IMV=-0.1490, accuracy=0.4124

Mutagenicity seed 48 epoch 100/200: IMV=0.3898, accuracy=0.7220

AIDS seed 49 epoch 50/200: IMV=0.2287, accuracy=0.9733

AIDS seed 48 epoch 25/200: IMV=0.1816, accuracy=0.9367
Mutagenicity seed 49 epoch 150/200: IMV=0.3995, accuracy=0.7404

Mutagenicity seed 50 epoch 200/200: IMV=0.4149, accuracy=0.7573

AIDS seed 46 epoch 0/200: IMV=-0.3094, accuracy=0.8033

AIDS seed 46 epoch 25/200: IMV=0.1974, accuracy=0.9500
AIDS seed 48 epoch 50/200: IMV=0.2217, accuracy=0.9600

AIDS seed 49 epoch 75/200: IMV=0.2351, accuracy=0.9867

Mutagenicity seed 48 epoch 125/200: IMV=0.3996, accuracy=0.7250

AIDS seed 46 epoch 50/200: IMV=0.2329, accuracy=0.9733

AIDS seed 48 epoch 75/200: IMV=0.2345, accuracy=0.9833

AIDS seed 49 epoch 100/200: IMV=0.2348, accuracy=0.9867

AIDS seed 46 epoch 75/200: IMV=0.2388, accuracy=0.9867

Mutagenicity seed 49 epoch 175/200: IMV=0.4048, accuracy=0.7404

AIDS seed 46 epoch 100/200: IMV=0.2387, accuracy=0.9833

AIDS seed 49 epoch 125/200: IMV=0.2347, accuracy=0.9900

AIDS seed 48 epoch 100/200: IMV=0.2381, accuracy=0.9900

Mutagenicity seed 48 epoch 150/200: IMV=0.4058, accuracy=0.7327

AIDS seed 46 epoch 125/200: IMV=0.2396, accuracy=0.9867

AIDS seed 49 epoch 150/200: IMV=0.2338, accuracy=0.9900

AIDS seed 48 epoch 125/200: IMV=0.2389, accuracy=0.9933

DD seed 43 epoch 25/200: IMV=0.0207, accuracy=0.5876

AIDS seed 46 epoch 150/200: IMV=0.2397, accuracy=0.9833

AIDS seed 49 epoch 175/200: IMV=0.2325, accuracy=0.9833

AIDS seed 48 epoch 150/200: IMV=0.2392, accuracy=0.9900

AIDS seed 46 epoch 175/200: IMV=0.2396, accuracy=0.9833

AIDS seed 49 epoch 200/200: IMV=0.2324, accuracy=0.9867

AIDS seed 48 epoch 175/200: IMV=0.2399, accuracy=0.9933

DD seed 45 epoch 0/200: IMV=-0.1490, accuracy=0.4124
Mutagenicity seed 49 epoch 200/200: IMV=0.4056, accuracy=0.7404

AIDS seed 45 epoch 0/200: IMV=-0.3750, accuracy=0.3600

AIDS seed 46 epoch 200/200: IMV=0.2391, accuracy=0.9833

DD seed 42 epoch 0/200: IMV=-0.1490, accuracy=0.4124

AIDS seed 45 epoch 25/200: IMV=0.1870, accuracy=0.9133
AIDS seed 48 epoch 200/200: IMV=0.2405, accuracy=0.9933

Mutagenicity seed 48 epoch 175/200: IMV=0.4052, accuracy=0.7327

DD seed 44 epoch 0/200: IMV=-0.0406, accuracy=0.5876

AIDS seed 45 epoch 50/200: IMV=0.2206, accuracy=0.9767

AIDS seed 45 epoch 75/200: IMV=0.2294, accuracy=0.9767

AIDS seed 45 epoch 100/200: IMV=0.2312, accuracy=0.9800

AIDS seed 45 epoch 125/200: IMV=0.2322, accuracy=0.9800

Mutagenicity seed 48 epoch 200/200: IMV=0.4057, accuracy=0.7343
DD seed 43 epoch 50/200: IMV=0.1243, accuracy=0.6158

AIDS seed 44 epoch 0/200: IMV=-0.2244, accuracy=0.8033

AIDS seed 45 epoch 150/200: IMV=0.2328, accuracy=0.9800

AIDS seed 44 epoch 25/200: IMV=0.2019, accuracy=0.9467

AIDS seed 45 epoch 175/200: IMV=0.2327, accuracy=0.9800

AIDS seed 44 epoch 50/200: IMV=0.2297, accuracy=0.9667

DD seed 42 epoch 25/200: IMV=0.0106, accuracy=0.5876

AIDS seed 45 epoch 200/200: IMV=0.2333, accuracy=0.9800

AIDS seed 51 epoch 0/200: IMV=-0.3750, accuracy=0.2000

AIDS seed 44 epoch 75/200: IMV=0.2336, accuracy=0.9767

AIDS seed 44 epoch 100/200: IMV=0.2343, accuracy=0.9767
AIDS seed 51 epoch 25/200: IMV=0.2110, accuracy=0.9633

AIDS seed 44 epoch 125/200: IMV=0.2355, accuracy=0.9767
DD seed 44 epoch 25/200: IMV=0.0182, accuracy=0.5876

DD seed 45 epoch 25/200: IMV=0.0210, accuracy=0.5876

AIDS seed 51 epoch 50/200: IMV=0.2301, accuracy=0.9800

AIDS seed 44 epoch 150/200: IMV=0.2348, accuracy=0.9767

DD seed 43 epoch 75/200: IMV=0.2586, accuracy=0.7345

AIDS seed 51 epoch 75/200: IMV=0.2399, accuracy=0.9833

AIDS seed 44 epoch 175/200: IMV=0.2349, accuracy=0.9767

AIDS seed 51 epoch 100/200: IMV=0.2439, accuracy=0.9900
AIDS seed 44 epoch 200/200: IMV=0.2341, accuracy=0.9767
AIDS seed 50 epoch 0/200: IMV=-0.3750, accuracy=0.2233

AIDS seed 51 epoch 125/200: IMV=0.2452, accuracy=0.9933
AIDS seed 50 epoch 25/200: IMV=0.2070, accuracy=0.9600

AIDS seed 50 epoch 50/200: IMV=0.2296, accuracy=0.9800

AIDS seed 51 epoch 150/200: IMV=0.2452, accuracy=0.9900

AIDS seed 50 epoch 75/200: IMV=0.2342, accuracy=0.9900

AIDS seed 51 epoch 175/200: IMV=0.2453, accuracy=0.9900

DD seed 42 epoch 50/200: IMV=0.1057, accuracy=0.5932

AIDS seed 50 epoch 100/200: IMV=0.2348, accuracy=0.9867

AIDS seed 51 epoch 200/200: IMV=0.2452, accuracy=0.9900

DD seed 47 epoch 0/200: IMV=-0.0361, accuracy=0.5876

AIDS seed 50 epoch 125/200: IMV=0.2349, accuracy=0.9900

DD seed 43 epoch 100/200: IMV=0.2872, accuracy=0.7458

AIDS seed 50 epoch 150/200: IMV=0.2346, accuracy=0.9900

AIDS seed 50 epoch 175/200: IMV=0.2342, accuracy=0.9867

DD seed 44 epoch 50/200: IMV=0.0971, accuracy=0.6215

AIDS seed 50 epoch 200/200: IMV=0.2323, accuracy=0.9867

DD seed 45 epoch 50/200: IMV=0.1135, accuracy=0.6045

DD seed 46 epoch 0/200: IMV=-0.0531, accuracy=0.5876

DD seed 43 epoch 125/200: IMV=0.2923, accuracy=0.7288

DD seed 47 epoch 25/200: IMV=0.0351, accuracy=0.5876

DD seed 42 epoch 75/200: IMV=0.2310, accuracy=0.7232

DD seed 43 epoch 150/200: IMV=0.2989, accuracy=0.7458

DD seed 47 epoch 50/200: IMV=0.1970, accuracy=0.6836

DD seed 44 epoch 75/200: IMV=0.1238, accuracy=0.6554

DD seed 46 epoch 25/200: IMV=0.0139, accuracy=0.5876

DD seed 45 epoch 75/200: IMV=0.2194, accuracy=0.7062

DD seed 42 epoch 100/200: IMV=0.2456, accuracy=0.7119

DD seed 43 epoch 175/200: IMV=0.3089, accuracy=0.7514

DD seed 47 epoch 75/200: IMV=0.2597, accuracy=0.7062

DD seed 46 epoch 50/200: IMV=0.1277, accuracy=0.6497

DD seed 43 epoch 200/200: IMV=0.3151, accuracy=0.7571
DD seed 49 epoch 0/200: IMV=-0.1490, accuracy=0.4124

DD seed 44 epoch 100/200: IMV=0.1139, accuracy=0.6610

DD seed 45 epoch 100/200: IMV=0.2393, accuracy=0.7062
DD seed 42 epoch 125/200: IMV=0.2528, accuracy=0.7175

DD seed 46 epoch 75/200: IMV=0.1964, accuracy=0.7006

DD seed 47 epoch 100/200: IMV=0.2676, accuracy=0.7006

DD seed 49 epoch 25/200: IMV=0.0106, accuracy=0.5876

DD seed 44 epoch 125/200: IMV=0.1199, accuracy=0.6723

DD seed 47 epoch 125/200: IMV=0.2737, accuracy=0.7119

DD seed 46 epoch 100/200: IMV=0.2083, accuracy=0.7006

DD seed 42 epoch 150/200: IMV=0.2575, accuracy=0.7175

DD seed 45 epoch 125/200: IMV=0.2423, accuracy=0.6893

DD seed 49 epoch 50/200: IMV=0.0858, accuracy=0.5932

DD seed 47 epoch 150/200: IMV=0.2787, accuracy=0.7006

DD seed 44 epoch 150/200: IMV=0.1182, accuracy=0.6893

DD seed 46 epoch 125/200: IMV=0.2145, accuracy=0.6949

DD seed 49 epoch 75/200: IMV=0.2101, accuracy=0.7401

DD seed 42 epoch 175/200: IMV=0.2615, accuracy=0.7345

DD seed 47 epoch 175/200: IMV=0.2814, accuracy=0.7062

DD seed 45 epoch 150/200: IMV=0.2501, accuracy=0.7288

DD seed 42 epoch 200/200: IMV=0.2693, accuracy=0.7458
DD seed 48 epoch 0/200: IMV=-0.0561, accuracy=0.5876

DD seed 46 epoch 150/200: IMV=0.2213, accuracy=0.7062

DD seed 49 epoch 100/200: IMV=0.2483, accuracy=0.7288

DD seed 44 epoch 175/200: IMV=0.1173, accuracy=0.6780

DD seed 47 epoch 200/200: IMV=0.2844, accuracy=0.7232

DD seed 46 epoch 175/200: IMV=0.2283, accuracy=0.7345

DD seed 48 epoch 25/200: IMV=0.0138, accuracy=0.5876

DD seed 49 epoch 125/200: IMV=0.2634, accuracy=0.7345
DD seed 45 epoch 175/200: IMV=0.2529, accuracy=0.7119

DD seed 44 epoch 200/200: IMV=0.1173, accuracy=0.6780
DD seed 50 epoch 0/200: IMV=-0.1262, accuracy=0.5876

DD seed 46 epoch 200/200: IMV=0.2313, accuracy=0.7232

DD seed 48 epoch 50/200: IMV=0.1284, accuracy=0.6893

DD seed 49 epoch 150/200: IMV=0.2704, accuracy=0.7345

DD seed 50 epoch 25/200: IMV=0.0161, accuracy=0.5876

DD seed 45 epoch 200/200: IMV=0.2599, accuracy=0.7175
DD seed 51 epoch 0/200: IMV=-0.0414, accuracy=0.5876

DD seed 48 epoch 75/200: IMV=0.2014, accuracy=0.6836

DD seed 49 epoch 175/200: IMV=0.2682, accuracy=0.7401

DD seed 50 epoch 50/200: IMV=0.1252, accuracy=0.6384

DD seed 48 epoch 100/200: IMV=0.2046, accuracy=0.7062

DD seed 51 epoch 25/200: IMV=0.0285, accuracy=0.5876
DD seed 49 epoch 200/200: IMV=0.2792, accuracy=0.7401

DD seed 50 epoch 75/200: IMV=0.2436, accuracy=0.7288

DD seed 48 epoch 125/200: IMV=0.2050, accuracy=0.6893

DD seed 51 epoch 50/200: IMV=0.1696, accuracy=0.6780

DD seed 50 epoch 100/200: IMV=0.2864, accuracy=0.7571

DD seed 48 epoch 150/200: IMV=0.2097, accuracy=0.7006

DD seed 51 epoch 75/200: IMV=0.2523, accuracy=0.7288

DD seed 50 epoch 125/200: IMV=0.3027, accuracy=0.7401

DD seed 48 epoch 175/200: IMV=0.2128, accuracy=0.7119

DD seed 51 epoch 100/200: IMV=0.2733, accuracy=0.7401

DD seed 50 epoch 150/200: IMV=0.3212, accuracy=0.7797
DD seed 48 epoch 200/200: IMV=0.2192, accuracy=0.7175

DD seed 51 epoch 125/200: IMV=0.2792, accuracy=0.7458

DD seed 50 epoch 175/200: IMV=0.3243, accuracy=0.7684

DD seed 51 epoch 150/200: IMV=0.2882, accuracy=0.7571

DD seed 50 epoch 200/200: IMV=0.3399, accuracy=0.7740

DD seed 51 epoch 175/200: IMV=0.2957, accuracy=0.7514

DD seed 51 epoch 200/200: IMV=0.3002, accuracy=0.7458

Completed results: /home/jinx/.cache/imv/notebook_artifacts/gnn_training/results

Completed GNN results: /home/jinx/.cache/imv/notebook_artifacts/gnn_training/results

In [3]:
final_test = epoch_metrics.query("split == 'test' and epoch == @CONFIG.epochs")
final_summary = final_test.groupby("dataset", sort=False)[
    ["imv", "accuracy", "precision", "recall", "balanced_accuracy", "roc_auc", "brier", "log_loss"]
].agg(["mean", "std", "count"])
final_summary

                   imv                  accuracy                 precision  \
                  mean       std count      mean       std count      mean
dataset
PROTEINS      0.212052  0.048759    10  0.711377  0.027772    10  0.674938
NCI1          0.397838  0.051240    10  0.694003  0.015747    10  0.692744
NCI109        0.374870  0.037716    10  0.684194  0.019456    10  0.673002
Mutagenicity  0.438739  0.029058    10  0.757604  0.017556    10  0.725695
AIDS          0.237739  0.004618    10  0.984000  0.005622    10  0.988840
DD            0.261581  0.062278    10  0.732203  0.026526    10  0.742695

                                recall  ... balanced_accuracy   roc_auc  \
                   std count      mean  ...             count      mean
dataset                                 ...
PROTEINS      0.039508    10  0.548310  ...                10  0.734824
NCI1          0.023564    10  0.702589  ...                10  0.747890
NCI109        0.027966    10  0.730128  ...                10  0.732406
Mutagenicity  0.025872    10  0.734828  ...                10  0.836639
AIDS          0.006920    10  0.991250  ...                10  0.993840
DD            0.043014    10  0.536986  ...                10  0.761301

                                 brier                  log_loss            \
                   std count      mean       std count      mean       std
dataset
PROTEINS      0.036154    10  0.200066  0.011456    10  0.587760  0.026792
NCI1          0.012689    10  0.204864  0.004136    10  0.609488  0.020595
NCI109        0.015845    10  0.210973  0.005600    10  0.616893  0.015546
Mutagenicity  0.015873    10  0.164066  0.007618    10  0.502693  0.022214
AIDS          0.005912    10  0.012072  0.004109    10  0.054440  0.017378
DD            0.040599    10  0.190149  0.013925    10  0.568681  0.035235


             count
dataset
PROTEINS        10
NCI1            10
NCI109          10
Mutagenicity    10
AIDS            10
DD              10

[6 rows x 24 columns]

In [4]:
imv_coverage = epoch_metrics.groupby(["dataset", "split"])["imv_status"].value_counts().unstack(fill_value=0)
imv_coverage

imv_status               chance_boundary  defined
dataset      split
AIDS         test                      8     2002
             validation                8     2002
DD           test                     12     1998
             validation               12     1998
Mutagenicity test                      8     2002
             validation                8     2002
NCI1         test                     11     1999
             validation               12     1998
NCI109       test                     13     1997
             validation               13     1997
PROTEINS     test                     15     1995
             validation               14     1996

## Rebuild only the GNN experiment and publication plots

From the repository root, in an environment with `requirements.txt` installed:

```bash
IMV_FORCE_RECOMPUTE=0 jupyter nbconvert --execute --to notebook --inplace --ExecutePreprocessor.timeout=-1 src/empirical/gnn/gnn_training.ipynb
jupyter nbconvert --execute --to notebook --inplace src/plotter/plotter.ipynb
```

The second command only reads saved results. It produces PDF figures with Helvetica and `Spectral_r`. No PNG/SVG figure files are saved. The existing ablation CSVs are also required for the combined plotter.